// Version is injected at build time from package.json via vite.config.ts (define: __APP_VERSION__)
// Do not edit this file manually — bump the version in package.json instead.
export const APP_VERSION = __APP_VERSION__
